cmake_minimum_required(VERSION 3.27)
project(advent2025_cpp)

set(CMAKE_CXX_STANDARD 17)

add_executable(day_1 day_1.cpp)
add_executable(day_1_part2 day_1.5.cpp)

add_executable(day_2 day_2.cpp)
add_executable(day_2_part2 day_2.5.cpp)

add_executable(day_3 day_3.cpp)
add_executable(day_3_part2 day_3.5.cpp)

add_executable(day_4_test day_4_test.cpp)
add_executable(day_4 day_4.cpp)
add_executable(day_4_part2 day_4.5.cpp)

add_executable(day_5_test day_5_test.cpp)
add_executable(day_5 day_5.cpp)
add_executable(day_5_part2 day_5.5.cpp)

add_executable(day_6 day_6.cpp)
#add_executable(day_6_part2 day_6.5.cpp)
#
#add_executable(day_7 day_7.cpp)
#add_executable(day_7_part2 day_7.5.cpp)
#
#add_executable(day_8 day_8.cpp)
#add_executable(day_8_part2 day_8.5.cpp)
#
#add_executable(day_9 day_9.cpp)
#add_executable(day_9_part2 day_9.5.cpp)
#
#add_executable(day_10 day_10.cpp)
#add_executable(day_10_part2 day_10.5.cpp)
#
#add_executable(day_11 day_11.cpp)
#add_executable(day_11_part2 day_11.5.cpp)
#
#add_executable(day_12 day_12.cpp)
#add_executable(day_12_part2 day_12.5.cpp)
